version: "3.7"
services:
  laravel:
    image: lorisleiva/laravel-docker:7.4
    environment:
      - TZ='America/Recife'
    working_dir: /var/www/
    volumes:
      - ./laravel/:/var/www
    command: "bash startupPresentation.sh"
    ports:
      - 8005:8005