version: "3.7"
services:
  laravel:
    image: lorisleiva/laravel-docker:7.4
    environment:
      - TZ='America/Recife'
    working_dir: /var/www/
    volumes:
      - ./laravel/:/var/www
    command: bash -c "composer install && php artisan storage:link && php artisan serve --host=0.0.0.0 --port=8005"
    ports:
      - 8005:8005